config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, except: [:create]
    
    def create
        @task = @project.tasks.create(task_params)
        redirect_to @project
    end

    def destroy
        if @task.destroy
            flash[:success] = "Task was deleted."
        else
            flash[:error] = "Task was not deleted."
        end
        redirect_to @project
    end
    
    def complete
        @task.update_attribute(:completed_at, Time.now)
        redirect_to @project, notice: "Task Completed"
    end

    private
    def set_project
        @project = Project.find(params[:project_id])
    end
    
    def set_task
        @task = @project.tasks.find(params[:id])
    end
    

    def task_params
        params[:task].permit(:content)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <script src="https://use.fontawesome.com/825832361a.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<div id="todo_items_wrapper">
  <%= render @project.tasks %>
  <div id="form">
    <%= render "tasks/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
    <%= f.text_field :content, placeholder: "New Task" %>
    <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div>
    <% if task.completed? %>
        <div class="complete">
            <%= link_to complete_project_task_path(@project, task.id), method: :patch do %>
                <i style="opacity:0.4;" class="fa fa-check"></i>
            <% end %>
        </div>
        <div class="task">
            <p style="opacity: 0.4;"><strike><%= task.content %></strike></p>
        </div>
        <div class="trash">
            <%= link_to project_task_path(@project, task.id), method: :delete, data: {confirm: "Are you sure?" } do %>
                <i class="fa fa-trash"></i>
            <% end %>
        </div>
    <% else %>
        <div class="complete">
            <%= link_to complete_project_task_path(@project, task.id), method: :patch do %>
                <i class="fa fa-check"></i>
            <% end %>
        </div>
        <div class="task">
            <p><%= task.content %></p>
        </div>
        <div class="trash">
            <%= link_to project_task_path(@project, task.id), method: :delete, data: {confirm: "Are you sure?" } do %>
                <i class="fa fa-trash"></i>
            <% end %>
        </div>
    <% end %>
</div>